# Site Settings
title: Kenichi Ebinuma
url: 'https://ebkn12.github.io'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-2
# style: styles-3
# style: styles-4
# style: styles-5
style: styles-6

#Profile information
name: Kenichi Ebinuma
tagline: University student, Web Developer
pic: profile.jpg
summary: "I'm a 2nd grade of university student at Meiji University. I like playing tennis, watching movies and developing some products. I often create some products of web programing and Ruby and JavaScript are my favorite language. I want to create product which changes our lifestyles."

#sidebar links
github: ebkn12
twitter: '@ebikentennis'
facebook: 'kenichi.ebinuma.9'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-112759202-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
